# Generated by Django 3.2.8 on 2021-10-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0013_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='blog_images'),
        ),
    ]
