# Generated by Django 3.2.8 on 2021-10-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0021_auto_20211020_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='blog_images'),
        ),
    ]
