# Generated by Django 3.2.8 on 2021-11-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0025_delete_likefunc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('update_post', 'update post'),)},
        ),
    ]
