# Generated by Django 3.2.8 on 2021-11-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0027_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('update_post', 'update post'),)},
        ),
    ]
