# Generated by Django 3.2.8 on 2021-11-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0028_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
