# Generated by Django 3.2.8 on 2022-03-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0029_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
